set(PCEM_PRIVATE_API ${PCEM_PRIVATE_API}
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/cpu.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/386_common.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/386_ops.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/8087.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_flags.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_3dnow.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_arith.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_atomic.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_bcd.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_bit.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_bitscan.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_call.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_cyrix.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_flag.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_fpu.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_inc_dec.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_int.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_io.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_jump.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_misc.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_mmx_arith.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_mmx_cmp.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_mmx.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_mmx_logic.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_mmx_mov.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_mmx_pack.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_mmx_shift.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_mov_ctrl.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_mov.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_mov_seg.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_movx.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_msr.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_mul.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_pmode.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_prefix.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_rep.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_ret.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_set.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_shift.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_stack.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_string.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x86_ops_xchg.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x87.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x87_ops_arith.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x87_ops.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x87_ops_loadstore.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x87_ops_misc.h
        ${CMAKE_SOURCE_DIR}/includes/private/cpu/x87_timings.h
        )

set(PCEM_SRC ${PCEM_SRC}
        cpu/386.c
        cpu/386_common.c
        cpu/386_dynarec.c
        cpu/386_dynarec_ops.c
        cpu/808x.c
        cpu/cpu.c
        cpu/cpu_tables.c
        cpu/x86seg.c
        cpu/x87.c
        cpu/x87_timings.c
        )