set(PCEM_SRC_DEVICES
        devices/cassette.c
        devices/device.c
        devices/esdi_at.c
        devices/f82c710_upc.c
        devices/nvr.c
        devices/ps2_nvr.c
        devices/sis496.c
        )