if(USE_EXPERIMENTAL AND USE_EXPERIMENTAL_PGC)
        set(PCEM_DEFINES ${PCEM_DEFINES} USE_EXPERIMENTAL_PGC)
endif()

set(PCEM_SRC_VIDEO
        video/vid_ati18800.c
        video/vid_ati28800.c
        video/vid_ati68860_ramdac.c
        video/vid_ati_eeprom.c
        video/vid_ati_mach64.c
        video/vid_cga.c
        video/vid_cl5429.c
        video/vid_colorplus.c
        video/vid_compaq_cga.c
        video/vid_ddc.c
        video/vid_ega.c
        video/vid_et4000.c
        video/vid_et4000w32.c
        video/vid_genius.c
        video/vid_hercules.c
        video/vid_ht216.c
        video/vid_icd2061.c
        video/vid_ics2595.c
        video/vid_im1024.c
        video/vid_incolor.c
        video/vid_mda.c
        video/vid_mga.c
        video/vid_olivetti_m24.c
        video/vid_oti037.c
        video/vid_oti067.c
        video/vid_paradise.c
        video/vid_pc1512.c
        video/vid_pc1640.c
        video/vid_pc200.c
        video/vid_pcjr.c
        video/vid_pgc.c
        video/vid_ps1_svga.c
        video/vid_s3.c
        video/vid_s3_virge.c
        video/vid_sdac_ramdac.c
        video/vid_sigma.c
        video/vid_stg_ramdac.c
        video/vid_svga.c
        video/vid_svga_render.c
        video/vid_t1000.c
        video/vid_t3100e.c
        video/vid_tandy.c
        video/vid_tandysl.c
        video/vid_tgui9440.c
        video/vid_tkd8001_ramdac.c
        video/vid_tvga.c
        video/vid_tvp3026_ramdac.c
        video/vid_unk_ramdac.c
        video/vid_vga.c
        video/vid_voodoo.c
        video/vid_voodoo_banshee.c
        video/vid_voodoo_banshee_blitter.c
        video/vid_voodoo_blitter.c
        video/vid_voodoo_display.c
        video/vid_voodoo_fb.c
        video/vid_voodoo_fifo.c
        video/vid_voodoo_reg.c
        video/vid_voodoo_render.c
        video/vid_voodoo_setup.c
        video/vid_voodoo_texture.c
        video/vid_wy700.c
        video/video.c
        )