set(PCEM_SRC_MODELS
        models/82091aa.c
        models/acc2036.c
        models/acc2168.c
        models/acc3221.c
        models/acer386sx.c
        models/ali1429.c
        models/amstrad.c
        models/cbm_io.c
        models/cmd640.c
        models/compaq.c
        models/cs8230.c
        models/dells200.c
        models/dma.c
        models/headland.c
        models/i430fx.c
        models/i430hx.c
        models/i430lx.c
        models/i430vx.c
        models/i440bx.c
        models/i440fx.c
        models/intel.c
        models/jim.c
        models/laserxt.c
        models/model.c
        models/mvp3.c
        models/neat.c
        models/nmi.c
        models/nvr_tc8521.c
        models/olivetti_m24.c
        models/opti495.c
        models/pc87306.c
        models/pc87307.c
        models/pic.c
        models/piix.c
        models/piix_pm.c
        models/pit.c
        models/ps1.c
        models/ps2.c
        models/ps2_mca.c
        models/scamp.c
        models/scat.c
        models/serial.c
        models/sio.c
        models/sl82c460.c
        models/superxt.c
        models/t1000.c
        models/t3100e.c
        models/um8669f.c
        models/um8881f.c
        models/vl82c480.c
        models/vt82c586b.c
        models/w83877tf.c
        models/w83977tf.c
        models/wd76c10.c
        models/xi8088.c
        models/zenith.c
        )