set(PCEM_PRIVATE_API ${PCEM_PRIVATE_API}
        ${CMAKE_SOURCE_DIR}/includes/private/models/82091aa.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/acc2036.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/acc2168.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/acc3221.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/acer386sx.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/ali1429.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/amstrad.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/cbm_io.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/cmd640.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/compaq.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/cs8230.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/dells200.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/dma.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/grid.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/headland.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/i430fx.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/i430hx.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/i430lx.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/i430vx.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/i440bx.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/i440fx.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/intel.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/jim.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/laserxt.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/model.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/mvp3.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/neat.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/nmi.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/olivetti_m24.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/opti495.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/pc87306.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/pc87307.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/pic.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/piix.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/piix_pm.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/pit.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/ps1.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/ps2.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/ps2_mca.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/scat.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/serial.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/sio.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/sl82c460.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/superxt.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/t1000.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/t3100e.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/um8669f.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/um8881f.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/vl82c480.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/vt82c586b.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/w83877tf.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/w83977tf.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/wd76c10.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/xi8088.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/zenith.h
        )

set(PCEM_SRC ${PCEM_SRC}
        models/82091aa.c
        models/acc2036.c
        models/acc2168.c
        models/acc3221.c
        models/acer386sx.c
        models/ali1429.c
        models/amstrad.c
        models/cbm_io.c
        models/cmd640.c
        models/compaq.c
        models/cs8230.c
        models/dells200.c
        models/dma.c
        models/grid.c
        models/headland.c
        models/i430fx.c
        models/i430hx.c
        models/i430lx.c
        models/i430vx.c
        models/i440bx.c
        models/i440fx.c
        models/intel.c
        models/jim.c
        models/laserxt.c
        models/model.c
        models/mvp3.c
        models/neat.c
        models/nmi.c
        models/nvr_tc8521.c
        models/olivetti_m24.c
        models/opti495.c
        models/pc87306.c
        models/pc87307.c
        models/pic.c
        models/piix.c
        models/piix_pm.c
        models/pit.c
        models/ps1.c
        models/ps2.c
        models/ps2_mca.c
        models/scamp.c
        models/scat.c
        models/serial.c
        models/sio.c
        models/sl82c460.c
        models/superxt.c
        models/t1000.c
        models/t3100e.c
        models/um8669f.c
        models/um8881f.c
        models/vl82c480.c
        models/vt82c586b.c
        models/w83877tf.c
        models/w83977tf.c
        models/wd76c10.c
        models/xi8088.c
        models/zenith.c
        )