set(PCEM_DEFINES ${PCEM_DEFINES} PLUGIN_DIR="${CMAKE_INSTALL_PREFIX}/${PCEM_PLUGIN_DIR}")

if(CMAKE_BUILD_TYPE STREQUAL "Debug" OR CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
        set(PCEM_DEFINES ${PCEM_DEFINES} DEBUG)

        if(PCEM_SLIRP_DEBUG)
                set(PCEM_DEFINES ${PCEM_DEFINES} SLIRP_DEBUG)
        endif()
        if(PCEM_RECOMPILER_DEBUG)
                set(PCEM_DEFINES ${PCEM_DEFINES} RECOMPILER_DEBUG)
        endif()
        if(PCEM_NE2000_DEBUG)
                set(PCEM_DEFINES ${PCEM_DEFINES} NE2000_DEBUG)
        endif()
        if(PCEM_EMU8K_DEBUG_REGISTERS)
                set(PCEM_DEFINES ${PCEM_DEFINES} EMU8K_DEBUG_REGISTERS)
        endif()
        if(PCEM_SB_DSP_RECORD_DEBUG)
                set(PCEM_DEFINES ${PCEM_DEFINES} SB_DSP_RECORD_DEBUG)
        endif()
        if(PCEM_MACH64_DEBUG)
                set(PCEM_DEFINES ${PCEM_DEFINES} MACH64_DEBUG)
        endif()
        if(PCEM_NE2000_DEBUG)
                set(PCEM_DEFINES ${PCEM_DEFINES} NE2000_DEBUG)
        endif()
        if(PCEM_DEBUG_EXTRA)
                set(PCEM_DEFINES ${PCEM_DEFINES} DEBUG_EXTRA)
        endif()
        if(PCEM_PRINTER_DEBUG)
                set(PCEM_DEFINES ${PCEM_DEFINES} PRINTER_DEBUG)
        endif()
else()
        set(PCEM_DEFINES ${PCEM_DEFINES} RELEASE_BUILD)
endif()
