set(PCEM_PRIVATE_HEADERS ${PCEM_PRIVATE_HEADERS}
	${CMAKE_SOURCE_DIR}/includes/private/386_common.h
	${CMAKE_SOURCE_DIR}/includes/private/386_ops.h
	${CMAKE_SOURCE_DIR}/includes/private/8087.h
	${CMAKE_SOURCE_DIR}/includes/private/82091aa.h
	${CMAKE_SOURCE_DIR}/includes/private/acc2036.h
	${CMAKE_SOURCE_DIR}/includes/private/acc2168.h
	${CMAKE_SOURCE_DIR}/includes/private/acc3221.h
	${CMAKE_SOURCE_DIR}/includes/private/acer386sx.h
	${CMAKE_SOURCE_DIR}/includes/private/ali1429.h
	${CMAKE_SOURCE_DIR}/includes/private/amstrad.h
	${CMAKE_SOURCE_DIR}/includes/private/bswap.h
	${CMAKE_SOURCE_DIR}/includes/private/cassette.h
	${CMAKE_SOURCE_DIR}/includes/private/cbm_io.h
	${CMAKE_SOURCE_DIR}/includes/private/cdrom-image.h
	${CMAKE_SOURCE_DIR}/includes/private/cdrom-ioctl.h
	${CMAKE_SOURCE_DIR}/includes/private/cdrom-null.h
	${CMAKE_SOURCE_DIR}/includes/private/cmd640.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_accumulate.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_allocator.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_backend_arm64_defs.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_backend_arm64.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_backend_arm64_ops.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_backend_arm_defs.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_backend_arm.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_backend_arm_ops.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_backend.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_backend_x86-64_defs.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_backend_x86-64.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_backend_x86-64_ops.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_backend_x86-64_ops_helpers.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_backend_x86-64_ops_sse.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_backend_x86_defs.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_backend_x86.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_backend_x86_ops_fpu.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_backend_x86_ops.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_backend_x86_ops_helpers.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_backend_x86_ops_sse.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ir_defs.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ir.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ops_3dnow.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ops_arith.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ops_branch.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ops_fpu_arith.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ops_fpu_constant.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ops_fpu_loadstore.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ops_fpu_misc.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ops.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ops_helpers.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ops_jump.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ops_logic.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ops_misc.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ops_mmx_arith.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ops_mmx_cmp.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ops_mmx_loadstore.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ops_mmx_logic.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ops_mmx_pack.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ops_mmx_shift.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ops_mov.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ops_shift.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_ops_stack.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_reg.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_timing_common.h
	${CMAKE_SOURCE_DIR}/includes/private/codegen_x86-64.h
	${CMAKE_SOURCE_DIR}/includes/private/compaq.h
	${CMAKE_SOURCE_DIR}/includes/private/config.h
	${CMAKE_SOURCE_DIR}/includes/private/cpu.h
	${CMAKE_SOURCE_DIR}/includes/private/cs8230.h
	${CMAKE_SOURCE_DIR}/includes/private/dells200.h
	${CMAKE_SOURCE_DIR}/includes/private/device.h
	${CMAKE_SOURCE_DIR}/includes/private/disc_fdi.h
	${CMAKE_SOURCE_DIR}/includes/private/disc.h
	${CMAKE_SOURCE_DIR}/includes/private/disc_img.h
	${CMAKE_SOURCE_DIR}/includes/private/disc_sector.h
	${CMAKE_SOURCE_DIR}/includes/private/dma.h
	${CMAKE_SOURCE_DIR}/includes/private/dosbox/cdrom.h
	${CMAKE_SOURCE_DIR}/includes/private/dosbox/dbopl.h
	${CMAKE_SOURCE_DIR}/includes/private/dosbox/nukedopl.h
	${CMAKE_SOURCE_DIR}/includes/private/dosbox/vid_cga_comp.h
	${CMAKE_SOURCE_DIR}/includes/private/esdi_at.h
	${CMAKE_SOURCE_DIR}/includes/private/f82c710_upc.h
	${CMAKE_SOURCE_DIR}/includes/private/fdc37c665.h
	${CMAKE_SOURCE_DIR}/includes/private/fdc37c93x.h
	${CMAKE_SOURCE_DIR}/includes/private/fdc.h
	${CMAKE_SOURCE_DIR}/includes/private/fdd.h
	${CMAKE_SOURCE_DIR}/includes/private/fdi2raw.h
	${CMAKE_SOURCE_DIR}/includes/private/filters.h
	${CMAKE_SOURCE_DIR}/includes/private/gameport.h
	${CMAKE_SOURCE_DIR}/includes/private/hdd_esdi.h
	${CMAKE_SOURCE_DIR}/includes/private/hdd_file.h
	${CMAKE_SOURCE_DIR}/includes/private/hdd.h
	${CMAKE_SOURCE_DIR}/includes/private/headland.h
	${CMAKE_SOURCE_DIR}/includes/private/i430fx.h
	${CMAKE_SOURCE_DIR}/includes/private/i430hx.h
	${CMAKE_SOURCE_DIR}/includes/private/i430lx.h
	${CMAKE_SOURCE_DIR}/includes/private/i430vx.h
	${CMAKE_SOURCE_DIR}/includes/private/i440bx.h
	${CMAKE_SOURCE_DIR}/includes/private/i440fx.h
	${CMAKE_SOURCE_DIR}/includes/private/ibm.h
	${CMAKE_SOURCE_DIR}/includes/private/ide_atapi.h
	${CMAKE_SOURCE_DIR}/includes/private/ide.h
	${CMAKE_SOURCE_DIR}/includes/private/ide_sff8038i.h
	${CMAKE_SOURCE_DIR}/includes/private/intel_flash.h
	${CMAKE_SOURCE_DIR}/includes/private/intel.h
	${CMAKE_SOURCE_DIR}/includes/private/io.h
	${CMAKE_SOURCE_DIR}/includes/private/jim.h
	${CMAKE_SOURCE_DIR}/includes/private/joystick_ch_flightstick_pro.h
	${CMAKE_SOURCE_DIR}/includes/private/joystick_standard.h
	${CMAKE_SOURCE_DIR}/includes/private/joystick_sw_pad.h
	${CMAKE_SOURCE_DIR}/includes/private/joystick_tm_fcs.h
	${CMAKE_SOURCE_DIR}/includes/private/keyboard_amstrad.h
	${CMAKE_SOURCE_DIR}/includes/private/keyboard_at.h
	${CMAKE_SOURCE_DIR}/includes/private/keyboard.h
	${CMAKE_SOURCE_DIR}/includes/private/keyboard_olim24.h
	${CMAKE_SOURCE_DIR}/includes/private/keyboard_pcjr.h
	${CMAKE_SOURCE_DIR}/includes/private/keyboard_xt.h
	${CMAKE_SOURCE_DIR}/includes/private/laserxt.h
	${CMAKE_SOURCE_DIR}/includes/private/lpt_dac.h
	${CMAKE_SOURCE_DIR}/includes/private/lpt_dss.h
	${CMAKE_SOURCE_DIR}/includes/private/lpt.h
	${CMAKE_SOURCE_DIR}/includes/private/mca.h
	${CMAKE_SOURCE_DIR}/includes/private/mem_bios.h
	${CMAKE_SOURCE_DIR}/includes/private/mem.h
	${CMAKE_SOURCE_DIR}/includes/private/mfm_at.h
	${CMAKE_SOURCE_DIR}/includes/private/mfm_xebec.h
	${CMAKE_SOURCE_DIR}/includes/private/minivhd/cwalk.h
	${CMAKE_SOURCE_DIR}/includes/private/minivhd/libxml2_encoding.h
	${CMAKE_SOURCE_DIR}/includes/private/minivhd/minivhd_create.h
	${CMAKE_SOURCE_DIR}/includes/private/minivhd/minivhd.h
	${CMAKE_SOURCE_DIR}/includes/private/minivhd/minivhd_internal.h
	${CMAKE_SOURCE_DIR}/includes/private/minivhd/minivhd_io.h
	${CMAKE_SOURCE_DIR}/includes/private/minivhd/minivhd_struct_rw.h
	${CMAKE_SOURCE_DIR}/includes/private/minivhd/minivhd_util.h
	${CMAKE_SOURCE_DIR}/includes/private/model.h
	${CMAKE_SOURCE_DIR}/includes/private/mouse.h
	${CMAKE_SOURCE_DIR}/includes/private/mouse_msystems.h
	${CMAKE_SOURCE_DIR}/includes/private/mouse_ps2.h
	${CMAKE_SOURCE_DIR}/includes/private/mouse_serial.h
	${CMAKE_SOURCE_DIR}/includes/private/mvp3.h
	${CMAKE_SOURCE_DIR}/includes/private/ne2000.h
	${CMAKE_SOURCE_DIR}/includes/private/neat.h
	${CMAKE_SOURCE_DIR}/includes/private/nethandler.h
	${CMAKE_SOURCE_DIR}/includes/private/nmi.h
	${CMAKE_SOURCE_DIR}/includes/private/nvr.h
	${CMAKE_SOURCE_DIR}/includes/private/nvr_tc8521.h
	${CMAKE_SOURCE_DIR}/includes/private/olivetti_m24.h
	${CMAKE_SOURCE_DIR}/includes/private/opti495.h
	${CMAKE_SOURCE_DIR}/includes/private/paths.h
	${CMAKE_SOURCE_DIR}/includes/private/pc87306.h
	${CMAKE_SOURCE_DIR}/includes/private/pc87307.h
	${CMAKE_SOURCE_DIR}/includes/private/pch.h
	${CMAKE_SOURCE_DIR}/includes/private/pci.h
	${CMAKE_SOURCE_DIR}/includes/private/pgc_palettes.h
	${CMAKE_SOURCE_DIR}/includes/private/pic.h
	${CMAKE_SOURCE_DIR}/includes/private/piix.h
	${CMAKE_SOURCE_DIR}/includes/private/piix_pm.h
	${CMAKE_SOURCE_DIR}/includes/private/pit.h
	${CMAKE_SOURCE_DIR}/includes/private/plat-dinput.h
	${CMAKE_SOURCE_DIR}/includes/private/plat-joystick.h
	${CMAKE_SOURCE_DIR}/includes/private/plat-keyboard.h
	${CMAKE_SOURCE_DIR}/includes/private/plat-midi.h
	${CMAKE_SOURCE_DIR}/includes/private/plat-mouse.h
	${CMAKE_SOURCE_DIR}/includes/private/ps1.h
	${CMAKE_SOURCE_DIR}/includes/private/ps2.h
	${CMAKE_SOURCE_DIR}/includes/private/ps2_mca.h
	${CMAKE_SOURCE_DIR}/includes/private/ps2_nvr.h
	${CMAKE_SOURCE_DIR}/includes/private/pzx.h
	${CMAKE_SOURCE_DIR}/includes/private/resid-fp/envelope.h
	${CMAKE_SOURCE_DIR}/includes/private/resid-fp/extfilt.h
	${CMAKE_SOURCE_DIR}/includes/private/resid-fp/filter.h
	${CMAKE_SOURCE_DIR}/includes/private/resid-fp/pot.h
	${CMAKE_SOURCE_DIR}/includes/private/resid-fp/siddefs-fp.h
	${CMAKE_SOURCE_DIR}/includes/private/resid-fp/sid.h
	${CMAKE_SOURCE_DIR}/includes/private/resid-fp/voice.h
	${CMAKE_SOURCE_DIR}/includes/private/resid-fp/wave.h
	${CMAKE_SOURCE_DIR}/includes/private/resources.h
	${CMAKE_SOURCE_DIR}/includes/private/rom.h
	${CMAKE_SOURCE_DIR}/includes/private/rtc.h
	${CMAKE_SOURCE_DIR}/includes/private/rtc_tc8521.h
	${CMAKE_SOURCE_DIR}/includes/private/scamp.h
	${CMAKE_SOURCE_DIR}/includes/private/scat.h
	${CMAKE_SOURCE_DIR}/includes/private/scsi_53c400.h
	${CMAKE_SOURCE_DIR}/includes/private/scsi_aha1540.h
	${CMAKE_SOURCE_DIR}/includes/private/scsi_cd.h
	${CMAKE_SOURCE_DIR}/includes/private/scsi.h
	${CMAKE_SOURCE_DIR}/includes/private/scsi_hd.h
	${CMAKE_SOURCE_DIR}/includes/private/scsi_ibm.h
	${CMAKE_SOURCE_DIR}/includes/private/scsi_zip.h
	${CMAKE_SOURCE_DIR}/includes/private/serial.h
	${CMAKE_SOURCE_DIR}/includes/private/sio.h
	${CMAKE_SOURCE_DIR}/includes/private/sis496.h
	${CMAKE_SOURCE_DIR}/includes/private/sl82c460.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/bootp.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/config.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/config-host.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/ctl.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/debug.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/icmp_var.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/if.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/ip.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/ip_icmp.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/libslirp.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/main.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/mbuf.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/misc.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/queue.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/sbuf.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/slirp_config.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/slirp.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/socket.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/tcp.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/tcpip.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/tcp_timer.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/tcp_var.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/tftp.h
	${CMAKE_SOURCE_DIR}/includes/private/slirp/udp.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_ad1848.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_adlibgold.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_adlib.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_audiopci.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_azt2316a.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_cms.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_dbopl.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_emu8k.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_gus.h
	${CMAKE_SOURCE_DIR}/includes/private/sound.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_mpu401_uart.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_opl.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_pas16.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_ps1.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_pssj.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_resid.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_sb_dsp.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_sb.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_sn76489.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_speaker.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_ssi2001.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_wss.h
	${CMAKE_SOURCE_DIR}/includes/private/sound_ym7128.h
	${CMAKE_SOURCE_DIR}/includes/private/sst39sf010.h
	${CMAKE_SOURCE_DIR}/includes/private/superxt.h
	${CMAKE_SOURCE_DIR}/includes/private/t1000.h
	${CMAKE_SOURCE_DIR}/includes/private/t3100e.h
	${CMAKE_SOURCE_DIR}/includes/private/tandy_eeprom.h
	${CMAKE_SOURCE_DIR}/includes/private/tandy_rom.h
	${CMAKE_SOURCE_DIR}/includes/private/thread.h
	${CMAKE_SOURCE_DIR}/includes/private/timer.h
	${CMAKE_SOURCE_DIR}/includes/private/um8669f.h
	${CMAKE_SOURCE_DIR}/includes/private/um8881f.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_ati18800.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_ati28800.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_ati68860_ramdac.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_ati_eeprom.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_ati_mach64.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_cga.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_cl5429.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_colorplus.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_compaq_cga.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_ddc.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_ega.h
	${CMAKE_SOURCE_DIR}/includes/private/video.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_et4000.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_et4000w32.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_genius.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_hercules.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_ht216.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_icd2061.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_ics2595.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_im1024.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_incolor.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_mda.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_mga.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_olivetti_m24.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_oti037.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_oti067.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_paradise.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_pc1512.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_pc1640.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_pc200.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_pcjr.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_pgc.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_ps1_svga.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_s3.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_s3_virge.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_sdac_ramdac.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_sigma.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_stg_ramdac.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_svga.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_svga_render.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_svga_render_remap.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_t1000.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_t3100e.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_tandy.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_tandysl.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_tgui9440.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_tkd8001_ramdac.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_tvga.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_tvp3026_ramdac.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_unk_ramdac.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_vga.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_voodoo_banshee_blitter.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_voodoo_banshee.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_voodoo_blitter.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_voodoo_codegen_x86-64.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_voodoo_codegen_x86.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_voodoo_common.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_voodoo_display.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_voodoo_dither.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_voodoo_fb.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_voodoo_fifo.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_voodoo.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_voodoo_reg.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_voodoo_regs.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_voodoo_render.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_voodoo_setup.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_voodoo_texture.h
	${CMAKE_SOURCE_DIR}/includes/private/vid_wy700.h
	${CMAKE_SOURCE_DIR}/includes/private/vl82c480.h
	${CMAKE_SOURCE_DIR}/includes/private/vt82c586b.h
	${CMAKE_SOURCE_DIR}/includes/private/w83877tf.h
	${CMAKE_SOURCE_DIR}/includes/private/w83977tf.h
	${CMAKE_SOURCE_DIR}/includes/private/wd76c10.h
	${CMAKE_SOURCE_DIR}/includes/private/wx-app.h
	${CMAKE_SOURCE_DIR}/includes/private/wx-common.h
	${CMAKE_SOURCE_DIR}/includes/private/wx-createdisc.h
	${CMAKE_SOURCE_DIR}/includes/private/wx-deviceconfig.h
	${CMAKE_SOURCE_DIR}/includes/private/wx-dialogbox.h
	${CMAKE_SOURCE_DIR}/includes/private/wx-display.h
	${CMAKE_SOURCE_DIR}/includes/private/wx-glsl.h
	${CMAKE_SOURCE_DIR}/includes/private/wx-glslp-parser.h
	${CMAKE_SOURCE_DIR}/includes/private/wx-hostconfig.h
	${CMAKE_SOURCE_DIR}/includes/private/wx-joystickconfig.h
	${CMAKE_SOURCE_DIR}/includes/private/wx-sdl2-glw.h
	${CMAKE_SOURCE_DIR}/includes/private/wx-sdl2.h
	${CMAKE_SOURCE_DIR}/includes/private/wx-sdl2-video-gl3.h
	${CMAKE_SOURCE_DIR}/includes/private/wx-sdl2-video.h
	${CMAKE_SOURCE_DIR}/includes/private/wx-sdl2-video-renderer.h
	${CMAKE_SOURCE_DIR}/includes/private/wx-shaderconfig.h
	${CMAKE_SOURCE_DIR}/includes/private/wx-status.h
	${CMAKE_SOURCE_DIR}/includes/private/wx-utils.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_flags.h
	${CMAKE_SOURCE_DIR}/includes/private/x86.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_3dnow.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_arith.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_atomic.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_bcd.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_bit.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_bitscan.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_call.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_cyrix.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_flag.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_fpu.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_inc_dec.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_int.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_io.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_jump.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_misc.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_mmx_arith.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_mmx_cmp.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_mmx.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_mmx_logic.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_mmx_mov.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_mmx_pack.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_mmx_shift.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_mov_ctrl.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_mov.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_mov_seg.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_movx.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_msr.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_mul.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_pmode.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_prefix.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_rep.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_ret.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_set.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_shift.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_stack.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_string.h
	${CMAKE_SOURCE_DIR}/includes/private/x86_ops_xchg.h
	${CMAKE_SOURCE_DIR}/includes/private/x87.h
	${CMAKE_SOURCE_DIR}/includes/private/x87_ops_arith.h
	${CMAKE_SOURCE_DIR}/includes/private/x87_ops.h
	${CMAKE_SOURCE_DIR}/includes/private/x87_ops_loadstore.h
	${CMAKE_SOURCE_DIR}/includes/private/x87_ops_misc.h
	${CMAKE_SOURCE_DIR}/includes/private/x87_timings.h
	${CMAKE_SOURCE_DIR}/includes/private/xi8088.h
	${CMAKE_SOURCE_DIR}/includes/private/xtide.h
	${CMAKE_SOURCE_DIR}/includes/private/zenith.h
)

set(PCEM_PUBLIC_HEADERS ${PCEM_PUBLIC_HEADERS}
	${CMAKE_SOURCE_DIR}/includes/public/pcem/devices.h
	${CMAKE_SOURCE_DIR}/includes/public/pcem/defines.h
	${CMAKE_SOURCE_DIR}/includes/public/pcem/cpu.h
)
